import requests
import json
import time
from typing import Dict, Any, List
from src.utils.logger import logger
from src.utils.config_loader import ConfigLoader

class FeishuClient:
    def __init__(self):
        self.config = ConfigLoader().config
        self.webhook_url = self.config['api_keys'].get('feishu_webhook')
        if not self.webhook_url:
            logger.error("Feishu Webhook URL is missing!")

    def send_card(self, analysis_result: Dict[str, Any]):
        """
        Sends an interactive card message to Feishu.
        """
        if not self.webhook_url:
            logger.warning("Skipping Feishu push (No URL)")
            return

        try:
            card_content = self._construct_card(analysis_result)
            payload = {
                "msg_type": "interactive",
                "card": card_content
            }
            
            response = requests.post(self.webhook_url, json=payload)
            response.raise_for_status()
            
            # Check Feishu response logic
            resp_json = response.json()
            if resp_json.get("code") != 0:
                logger.error(f"Feishu Error: {resp_json}")
            else:
                logger.info("Feishu notification sent successfully.")
                
        except Exception as e:
            logger.error(f"Failed to send Feishu message: {e}")

    def _construct_card(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Constructs the Feishu Interactive Card JSON.
        """
        market_sentiment = data.get("market_sentiment", "N/A")
        summary = data.get("summary", "No summary provided")
        actions = data.get("actions", [])

        # Color logic for Header
        header_color = "blue"
        if "DANGER" in str(actions) or "冰点" in market_sentiment:
            header_color = "red"
        elif "正常" in market_sentiment:
            header_color = "green"

        # Build Elements
        elements = [
            # 1. Market Sentiment & Summary
            {
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": f"**市场温度**: {market_sentiment}\n**午间综述**: {summary}"
                }
            },
            {"tag": "hr"}
        ]

        # 2. Key Actions (Stocks)
        for stock in actions:
            code = stock.get('code')
            name = stock.get('name')
            action = stock.get('action')
            reason = stock.get('reason')
            
            # Symbol & Color for Action
            emoji = "⚪️"
            if action == "DANGER": emoji = "🔴"
            elif action == "WATCH": emoji = "🟡"
            elif action == "HOLD": emoji = "🟢"
            
            stock_line = f"{emoji} **{name}** ({code}): **{action}**\n> {reason}"
            
            elements.append({
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": stock_line
                }
            })
        
        # 3. Footer
        elements.append({
            "tag": "note",
            "elements": [
                {
                    "tag": "plain_text",
                    "content": f"Generated by Project Sentinel • {time.strftime('%Y-%m-%d %H:%M')}"
                }
            ]
        })

        card = {
            "config": {
                "wide_screen_mode": True
            },
            "header": {
                "template": header_color,
                "title": {
                    "tag": "plain_text",
                    "content": "🤖 Sentinel 午间风控报告"
                }
            },
            "elements": elements
        }
        return card

if __name__ == "__main__":
    # Test
    client = FeishuClient()
    mock_data = {
        "market_sentiment": "冰点 (Cold)",
        "summary": "大盘缩量下跌，北向资金大幅流出，建议谨慎防御。",
        "actions": [
            {"code": "600519", "name": "贵州茅台", "action": "HOLD", "reason": "虽下跌但未破位"},
            {"code": "300750", "name": "宁德时代", "action": "DANGER", "reason": "放量跌破MA20"}
        ]
    }
    # client.send_card(mock_data) # Uncomment to test with real URL
    print(json.dumps(client._construct_card(mock_data), indent=2, ensure_ascii=False))
